/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WaypointService } from "../waypoint.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WaypointCreateInput } from "./WaypointCreateInput";
import { Waypoint } from "./Waypoint";
import { WaypointFindManyArgs } from "./WaypointFindManyArgs";
import { WaypointWhereUniqueInput } from "./WaypointWhereUniqueInput";
import { WaypointUpdateInput } from "./WaypointUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WaypointControllerBase {
  constructor(
    protected readonly service: WaypointService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Waypoint })
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWaypoint(
    @common.Body() data: WaypointCreateInput
  ): Promise<Waypoint> {
    return await this.service.createWaypoint({
      data: {
        ...data,

        route: data.route
          ? {
              connect: data.route,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        latitude: true,
        longitude: true,

        route: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Waypoint] })
  @ApiNestedQuery(WaypointFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waypoints(@common.Req() request: Request): Promise<Waypoint[]> {
    const args = plainToClass(WaypointFindManyArgs, request.query);
    return this.service.waypoints({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        latitude: true,
        longitude: true,

        route: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Waypoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waypoint(
    @common.Param() params: WaypointWhereUniqueInput
  ): Promise<Waypoint | null> {
    const result = await this.service.waypoint({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        latitude: true,
        longitude: true,

        route: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Waypoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWaypoint(
    @common.Param() params: WaypointWhereUniqueInput,
    @common.Body() data: WaypointUpdateInput
  ): Promise<Waypoint | null> {
    try {
      return await this.service.updateWaypoint({
        where: params,
        data: {
          ...data,

          route: data.route
            ? {
                connect: data.route,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          latitude: true,
          longitude: true,

          route: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Waypoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWaypoint(
    @common.Param() params: WaypointWhereUniqueInput
  ): Promise<Waypoint | null> {
    try {
      return await this.service.deleteWaypoint({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          latitude: true,
          longitude: true,

          route: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
