/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Waypoint } from "./Waypoint";
import { WaypointCountArgs } from "./WaypointCountArgs";
import { WaypointFindManyArgs } from "./WaypointFindManyArgs";
import { WaypointFindUniqueArgs } from "./WaypointFindUniqueArgs";
import { CreateWaypointArgs } from "./CreateWaypointArgs";
import { UpdateWaypointArgs } from "./UpdateWaypointArgs";
import { DeleteWaypointArgs } from "./DeleteWaypointArgs";
import { Route } from "../../route/base/Route";
import { WaypointService } from "../waypoint.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Waypoint)
export class WaypointResolverBase {
  constructor(
    protected readonly service: WaypointService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "read",
    possession: "any",
  })
  async _waypointsMeta(
    @graphql.Args() args: WaypointCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Waypoint])
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "read",
    possession: "any",
  })
  async waypoints(
    @graphql.Args() args: WaypointFindManyArgs
  ): Promise<Waypoint[]> {
    return this.service.waypoints(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Waypoint, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "read",
    possession: "own",
  })
  async waypoint(
    @graphql.Args() args: WaypointFindUniqueArgs
  ): Promise<Waypoint | null> {
    const result = await this.service.waypoint(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Waypoint)
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "create",
    possession: "any",
  })
  async createWaypoint(
    @graphql.Args() args: CreateWaypointArgs
  ): Promise<Waypoint> {
    return await this.service.createWaypoint({
      ...args,
      data: {
        ...args.data,

        route: args.data.route
          ? {
              connect: args.data.route,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Waypoint)
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "update",
    possession: "any",
  })
  async updateWaypoint(
    @graphql.Args() args: UpdateWaypointArgs
  ): Promise<Waypoint | null> {
    try {
      return await this.service.updateWaypoint({
        ...args,
        data: {
          ...args.data,

          route: args.data.route
            ? {
                connect: args.data.route,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Waypoint)
  @nestAccessControl.UseRoles({
    resource: "Waypoint",
    action: "delete",
    possession: "any",
  })
  async deleteWaypoint(
    @graphql.Args() args: DeleteWaypointArgs
  ): Promise<Waypoint | null> {
    try {
      return await this.service.deleteWaypoint(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Route, {
    nullable: true,
    name: "route",
  })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "read",
    possession: "any",
  })
  async getRoute(@graphql.Parent() parent: Waypoint): Promise<Route | null> {
    const result = await this.service.getRoute(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
